# Generated by Django 6.0.2 on 2026-03-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tovars', '0002_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewProduct',
        ),
    ]
