# Generated by Django 6.0.2 on 2026-02-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=50, verbose_name='Название книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Загрузите обложку')),
                ('category', models.CharField(choices=[('Детектив', 'Детектив'), ('Фантастика', 'Фантастика'), ('Роман', 'Роман'), ('Приключения', 'Приключения')], max_length=100, verbose_name='Категория книги')),
                ('url_audio_book', models.URLField(verbose_name='Ссылка на аудиокнигу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Книгу',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
